version: '3'
services:

  nginx:
    image: nginx:alpine
    ports:
      - "20000:80"
    volumes:
      - "~/DockerTasks/task28/dkr-30/nginx/default.conf:/etc/nginx/conf.d/default.conf"
    restart: unless-stopped
    depends_on:
      - voting 

  voting:
    build: ./
    ports:
      - "9000:9000"
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - mysql
      - redis
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/ping"]
      interval: 30s
      timeout: 30s
      retries: 5

  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: voting
      MYSQL_PASSWORD: voting
      MYSQL_USER: voting
      MYSQL_ROOT_PASSWORD: root
    restart: unless-stopped
    
  redis:
    image: redis:7.2.0
    restart: unless-stopped